# Generated by Django 3.2.4 on 2021-07-14 18:31

from django.db import migrations, models
import uploadvideo.validator


class Migration(migrations.Migration):

    dependencies = [
        ('uploadvideo', '0003_alter_videomodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='video',
            field=models.FileField(upload_to='video/%y', validators=[uploadvideo.validator.file_size]),
        ),
    ]
